shared/shared/core/key_types.py
shared/tests/unit/core/test_key_types.py
writer/tests/system/write/test_occ_locking.py
writer/tests/unit/postgresql_backend/test_sql_occ_locker_backend_service.py
writer/writer/postgresql_backend/sql_occ_locker_backend_service.py

(Deprecated) See #10
Locking a field in the fashion of `f_$_s` locks all fields matching the regex `f_.*_s`

Enable template field locking

---

Makefile
cli/create_initial_data.py
dc.test.yml
scripts/travis.sh

(sets up on #21)
First implementation of the example data import. Doesn't get called automatically yet, but is callable from inside the docker container with `python cli/create_initial_data.py`. It should however be possible to just call this script from the entrypoint. If done this way, the services will all be registered, the script is executed and then everything gets shutdown again just to boot again via the flask command. Since the startup is extremely fast, this shouldn't pose a problem, but maybe you've got a better solution.
In https://github.com/OpenSlides/OpenSlides/blob/bc19de95709ea049267ad455aa00686fcc10328d/docs/example-data.json#L2252 the field begins with an underscore, which is forbidden, so as a workaround I simply delete the field.

Example data

---

shared/shared/postgresql_backend/pg_connection_handler.py
writer/tests/system/write/test_write.py
writer/tests/unit/core/test_writer_service.py
writer/writer/core/writer_service.py

As mentioned by @ostcar, the writer must propagate the updates onto redis only after the transaction to the read db has been commited.

Fixed update propagation

---

README.md

I always copy the command from the readme and this bothered me :D

Fix some typos/commands in docs

---

scripts/system/wait-for-database.sh
writer/entrypoint.sh

fixes #85 
Reader doesn't wait, but I don't think this is an issue for now. It would only be if in the milliseconds when the reader is reader and the writer isn't a request came in, which is unlikely and even if, it would simply fail.

Move schema creation to writer

---

shared/shared/postgresql_backend/sql_query_helper.py
writer/tests/system/write/test_occ_locking.py

Forgot to pass the `table_alias` to each subsequent call, so multi-level filters would throw a 500 error...

Fix collection field lock with multiple filters

---

shared/shared/postgresql_backend/__init__.py
shared/shared/postgresql_backend/connection_handler.py
shared/shared/postgresql_backend/pg_connection_handler.py
shared/tests/unit/postgresql_backend/test_pg_connection_handler.py
writer/writer/core/writer_service.py

fixed 2 places where already-closed connection could lead to fatal errors. Added a test (which needs manual restarting of the postgres container) to provoke the OperationalError.

Fix handling of closed connections

---

writer/tests/unit/postgresql_backend/test_sql_occ_locker_backend_service.py
writer/writer/postgresql_backend/sql_occ_locker_backend_service.py

Often there will be multiple matches for the same fqfield. Filter them out by using a set instead of a list.

Remove duplicates from model locked error message

---

writer/tests/system/truncate_db/test_truncate_db.py
writer/tests/unit/postgresql_backend/test_sql_database_backend_service.py
writer/writer/postgresql_backend/sql_database_backend_service.py

Some data:
TRUNCATE TABLE:
Total: 3.0464930534362793
per call: 0.03046493053436279
DROP TABLE & rebuild from schema:
Total: 6.06488299369812
per call: 0.0606488299369812
DELETE FROM & restart sequences:
Total: 0.34722089767456055
per call: 0.0034722089767456055
maybe that will speed up the backend tests ;)

Improve truncate_db performance

---

tests/writer/system/write/test_write.py

Asserts, that the read DB always have the right values for meta_position (and meta_deleted) after writing to the datastore. There are no bugs, but I think there are bugs in #135, so we can reuse these tests there.

Added position tests

---

datastore/migrations/base_migration.py
datastore/migrations/events.py
datastore/migrations/migrater.py
datastore/migrations/migration_handler.py
tests/migrations/system/test_basic_migrate_cases.py
tests/migrations/system/test_event_overwrite.py
tests/migrations/system/test_wrong_new_events.py

- double calls to finalize was broken
- returning None in the migration class should definitly use the original event even when modification were done

Fixed migration bugs

---

cli/export_data_only.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
tests/migrations/system/conftest.py
tests/migrations/system/test_basic_migrate_cases.py
tests/migrations/system/test_check_latest.py
tests/migrations/system/test_errors_during_migration.py
tests/migrations/system/test_event_overwrite.py
tests/migrations/system/test_finalize_noop_migration.py
tests/migrations/system/test_migration_index_too_high.py
tests/migrations/system/test_migration_keyframes.py
tests/migrations/system/test_multiple_migrations_and_positions.py
tests/migrations/system/test_premade_migration_classes.py
tests/migrations/system/test_reset_migration.py
tests/migrations/system/test_sample_migrations.py
tests/migrations/system/test_wrong_new_events.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
tests/writer/system/write/test_migration_index.py

Use -1 as the default migration index (previously it was 1 if not the
import tools were used).
Supersedes #145

Changed initial migration index

---

.github/workflows/continuous_integration.yml
Makefile
datastore/migrations/core/events.py
datastore/migrations/core/migration_handler.py
datastore/shared/postgresql_backend/__init__.py
datastore/shared/postgresql_backend/connection_handler.py
datastore/shared/postgresql_backend/pg_connection_handler.py
datastore/shared/postgresql_backend/sql_event_types.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/environment_service.py
datastore/shared/services/read_database.py
datastore/writer/postgresql_backend/db_events.py
datastore/writer/postgresql_backend/event_translator.py
datastore/writer/postgresql_backend/sql_database_backend_service.py
docs/layout.md
tests/migrations/system/test_finalize_noop_migration.py
tests/reader/system/get/test_get.py
tests/reader/system/get_many/test_get_many.py
tests/reader/system/history_information/test_history_information.py
tests/reader/system/util.py
tests/shared/unit/postgresql_backend/test_pg_connection_handler.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
tests/util.py
tests/writer/integration/write/test_insert_events.py
tests/writer/system/util.py
tests/writer/system/write/test_multiple.py
tests/writer/unit/postgresql_backend/test_db_events.py
tests/writer/unit/postgresql_backend/test_event_translator.py
tests/writer/unit/postgresql_backend/test_sql_database_backend_service.py

First results of this (heavily WIP) PR: Tested sending 10000 update events which each changed 3 fields and deleted 3 fields. Measured times:
* before: 36s
* after: 2.3s
So, looking very promising! Will finalize these change and check for more places for improvement.

Performance improvements for write

---

requirements/requirements-general.txt

since a new release this leads to a traceback during intializing,
even if OTEL is not enabled.
see https://github.com/protocolbuffers/protobuf/issues/10051

pin version of protobuf

---

cli/import-events.sh

Reason for this is https://github.com/OpenSlides/OpenSlides/pull/6465
where I wanted to import SQL without needing to have the .sql file present in the containers file system.

add read-from-stdin to cli/import-events.sh for better compatibility

---

datastore/migrations/core/base_migration.py
datastore/migrations/core/events.py
datastore/shared/typing.py
tests/migrations/system/test_filter_empty_events.py
tests/migrations/system/test_migration_keyframes.py
tests/migrations/system/test_premade_migration_classes.py
tests/migrations/system/test_sample_migrations.py

- sort events per position, so create events are processed first to prevent errors related to not-yet created models
- filter out empty (list) update and delete field events after migrations
- fix some typing issues

Process create events first in migrations & remove empty events

---

datastore/writer/core/database.py
datastore/writer/core/writer_service.py
datastore/writer/flask_frontend/routes_handler.py
datastore/writer/postgresql_backend/sql_database_backend_service.py
tests/writer/system/test_write_action_worker.py

Lets use the write_action_worker route also for delete-events.
delete tests fail in datastore-tests  and backend action_worker-tests

Ba issue1680 action worker deletion

---

Dockerfile.debug

As of https://flask.palletsprojects.com/en/2.1.x/debugging/#external-debuggers it can cause unexpected behavior when using flask reload while an external debugger is attached. 
Therefore I removed debugpy from the dev Docker image. This is necessary because the datastore is currently crashing.

remove debugpy from development Dockerfile

---

datastore/migrations/core/migration_handler.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/read_database.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
tests/writer/system/write/test_migration_index.py

I think the way it was meant to be is that you shut down all containers except for the manage backend where the migrations are being run, run the migrations, and then start all other containers again. This way, everything works correctly. But if the datastore stays up during the migration (which happens in the backend), it has no way of knowing that the migration happened and will therefore still use the old migration index.
There is no reason that this should not have happened before - the responsive code has stayed the same for at least a year. Maybe you changed something about your instance setup workflow that made this error appear?
Anyway, to prevent this in the future, I removed the caching alltogether. This requires one more SQL query for each write request, but I think this is …

Remove caching for current migration index in ReadDatabase

---

Dockerfile
Dockerfile.debug
Dockerfile.dev
Dockerfile.test
dc.dev.yml
dc.external.yml
dc.test.yml
docker-compose.yml
system_tests/Dockerfile

Apart from debian being sensical on it's own, buster packages include postgres software for v11 - bookworm does for v15.

Use postgres 15 images + debian bookworm images

---

Dockerfile.debug
Dockerfile.dev
datastore/writer/postgresql_backend/sql_occ_locker_backend_service.py
scripts/start-flask.sh
tests/shared/unit/util/test_key_types.py
tests/writer/system/write/test_occ_locking.py

The filter part of the locked fields was not correctly parenthesized, so false positive broken locks could occur when called with multiple collection field filters, as happened in https://github.com/OpenSlides/openslides-client/pull/3101#pullrequestreview-1779842540.
Also, enabling the flask debug mode is now done via `FLASK_DEBUG` instead of via `FLASK_ENV`: https://flask.palletsprojects.com/en/2.3.x/config/#debug-mode
Also removed old template field tests.

Fix locked fields & dev setup

---

datastore/shared/util/key_types.py

The changes in xy lead to failing migration tests in the backend, as the template fields can no longer be written to the datastore: https://github.com/OpenSlides/openslides-backend/actions/runs/8062514334/job/22022403184
Although not the cleanest solution, I'm reverting this to quickly re-enable the tests.

Revert field regex change

---

Dockerfile
README.md
cli/trim_collectionfield_tables.py
docker-compose.yml
scripts/system/cron.sh
scripts/system/export-database-variables.sh
writer/entrypoint.sh

It seems to be generally frowned upon to run multiple services in one docker container, but I implemented it anyway for now, as it keeps our setup identical and does not require changes to all setup files, e.g., to include a new container. I currently run the script every night at 4am, which is pretty much randomly selected.

Add cronjob to trim collectionfield tables

---

datastore/migrations/core/migration_reader.py
tests/migrations/system/test_migration_reader.py

Closes Openslides/openslides-backend#2706

improve in memory migration reader
