Makefile
reader/.coveragerc
reader/Dockerfile.test
reader/Makefile
scripts/setup.cfg
scripts/travis.sh
shared/.coveragerc
shared/Dockerfile.test
shared/Makefile
writer/.coveragerc
writer/Dockerfile.test
writer/Makefile

Fixed coverage

---

Makefile
README.md
dc.prod.yml
reader/Dockerfile
scripts/make-targets
writer/Dockerfile.test
writer/entrypoint.sh

Needed to have the branch in the main repo for testing

Productive startup and Readme

---

reader/reader/core/reader_service.py
reader/tests/system/get_many/test_get_many.py

Fixed get_many with multiple requests with the same fqid

---

shared/shared/flask_frontend/errors.py

Added human readable error hints

---

writer/tests/integration/reserve_ids/test_reserve_ids.py
writer/tests/system/reserve_ids/test_reserve_ids.py
writer/tests/system/test_invalid_routes.py
writer/tests/system/util.py
writer/tests/unit/core/test_writer_service.py
writer/tests/unit/flask_frontend/test_json_handlers.py
writer/writer/core/writer.py
writer/writer/core/writer_service.py
writer/writer/flask_frontend/json_handlers.py
writer/writer/flask_frontend/routes.py

Renamed getIds to reserveIds

---

writer/tests/system/write/test_occ_locking.py
writer/tests/system/write/test_write.py
writer/writer/flask_frontend/routes.py

Changed `write` response code to 201

---

reader/reader/core/reader.py
reader/reader/core/reader_service.py
reader/tests/system/get_many/test_get_many.py
reader/tests/unit/core/test_reader_service.py
shared/shared/typing.py
shared/shared/util/__init__.py
shared/shared/util/filter.py
shared/shared/util/key_transforms.py
shared/shared/util/self_validating_dataclass.py
shared/tests/unit/util/test_key_transforms.py

as stated in https://github.com/OpenSlides/OpenSlides/pull/5342

Adjusts return type of get_many

---

writer/tests/system/util.py
writer/tests/unit/core/test_db_events.py
writer/tests/unit/postgresql_backend/test_sql_database_backend_service.py
writer/writer/core/db_events.py
writer/writer/redis_backend/connection_handler.py
writer/writer/redis_backend/redis_connection_handler.py
writer/writer/redis_backend/redis_messaging_backend_service.py

Changed redis format

---

shared/shared/postgresql_backend/sql_read_database_backend_service.py
shared/shared/services/read_database.py
shared/shared/typing.py
writer/tests/system/write/test_write.py
writer/tests/unit/core/test_event_executor.py
writer/writer/core/event_executor.py

Prevent deletion of models from lookup table on delete

---

reader/reader/core/reader_service.py
reader/tests/system/get_many/test_get_many.py
reader/tests/unit/core/test_reader_service.py

Add empty collections to get_many response

---

Dockerfile.dev

Remove duplicate ENTRYPOINT

---

README.md
cli/create_initial_data.py
docs/development.md

Update creation of initial data

---

writer/tests/integration/reserve_ids/test_reserve_ids.py
writer/tests/system/test_write_reserve_ids.py
writer/tests/system/write/test_write.py
writer/tests/unit/postgresql_backend/test_sql_database_backend_service.py
writer/writer/core/event_executor.py
writer/writer/postgresql_backend/sql_database_backend_service.py

Adjust id_sequences on create events

---

dc.dev.yml

Expose redis port for autoupdate service, as already done in prod setup
Add initial data creation

Fix dev startup

---

Dockerfile.prod
dc.dev.yml
shared/shared/postgresql_backend/pg_connection_handler.py
shared/shared/tests/fixtures.py
shared/tests/unit/postgresql_backend/test_pg_connection_handler.py
writer/tests/unit/core/test_writer_service.py
writer/writer/core/writer_service.py

Use a connection pool to support multiple parallel requests

---

reader/reader/app.py
shared/shared/__init__.py
shared/shared/util/__init__.py
shared/shared/util/logging.py
shared/tests/unit/test_create_base_application.py
shared/tests/unit/util/test_key_transforms.py
shared/tests/unit/util/test_logging.py
shared/tests/unit/util/test_self_validating_dataclass.py
writer/writer/app.py
writer/writer/core/writer_service.py
writer/writer/postgresql_backend/sql_database_backend_service.py

Add functional logging for dev and prod setup

---

Dockerfile
Dockerfile.dev
Dockerfile.prod
Makefile
dc.prod.yml
docs/layout.md
scripts/make-targets

Add NUM_WORKERS argument and clean up docker files

---

reader/tests/system/test_client.py

Test concurrent requests

---

Dockerfile
Dockerfile.dev
Dockerfile.prod
Dockerfile.test
Makefile
reader/reader/core/reader_service.py
reader/reader/flask_frontend/routes_handler.py
reader/tests/system/test_client.py
shared/shared/postgresql_backend/connection_handler.py
shared/shared/postgresql_backend/sql_read_database_backend_service.py
shared/tests/unit/postgresql_backend/test_sql_read_database_backend_service.py
system_tests/tests/test_full_system.py
writer/tests/unit/flask_frontend/test_json_handlers.py
writer/writer/core/event_executor.py
writer/writer/postgresql_backend/sql_database_backend_service.py
writer/writer/postgresql_backend/sql_occ_locker_backend_service.py

Everything works except the prod setup with git (see #89). Would probably just need to install git in the container though.

Change docker base image

---

reader/tests/system/filter/test_filter.py
shared/shared/postgresql_backend/sql_query_helper.py
shared/tests/unit/postgresql_backend/test_sql_query_helper.py

fixes https://github.com/OpenSlides/openslides-datastore-service/issues/97

Fix filter behaviour when value is None

---

dc.dev.yml
reader/reader/flask_frontend/json_handler.py
reader/reader/flask_frontend/routes.py
scripts/make-targets
shared/shared/flask_frontend/errors.py

Add better filter error description

---

reader/reader/core/reader.py
reader/reader/core/reader_service.py
reader/tests/system/filter/test_filter.py
reader/tests/unit/core/test_reader_service.py
shared/shared/postgresql_backend/sql_read_database_backend_service.py
shared/shared/services/read_database.py
shared/tests/unit/postgresql_backend/test_sql_read_database_backend_service.py

Renamed to `position` instead of `max_position` to be consistent with the other naming

Add position to filter route

---

cli/create_initial_data.py
writer/tests/system/write/test_write.py
writer/tests/unit/core/test_writer_service.py
writer/writer/core/messaging.py
writer/writer/core/writer.py
writer/writer/core/writer_service.py
writer/writer/flask_frontend/json_handlers.py
writer/writer/redis_backend/redis_messaging_backend_service.py

Accept list of write requests

---

README.md
reader/reader/core/reader_service.py
reader/tests/integration/get/test_get.py
reader/tests/unit/core/test_reader_service.py
shared/shared/postgresql_backend/pg_connection_handler.py
shared/tests/unit/postgresql_backend/test_pg_connection_handler.py
writer/tests/integration/reserve_ids/test_reserve_ids.py
writer/tests/integration/write/test_insert_events.py
writer/tests/integration/write/test_occ_locking.py
writer/tests/unit/core/test_writer_service.py
writer/writer/core/writer_service.py

Adjust retry handler

---

writer/tests/integration/write/test_occ_locking.py
writer/tests/system/write/test_occ_locking.py
writer/tests/unit/core/test_write_request.py
writer/writer/core/occ_locker.py
writer/writer/core/write_request.py
writer/writer/flask_frontend/json_handlers.py
writer/writer/postgresql_backend/sql_occ_locker_backend_service.py

implementing interface change from https://github.com/OpenSlides/OpenSlides/pull/6018

Lock collection field with array & empty filter

---

cli/create_initial_data.py
cli/import_data_only.py
datastore/migrations/migration_handler.py
datastore/shared/flask_frontend/errors.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/read_database.py
datastore/shared/util/__init__.py
datastore/shared/util/exceptions.py
datastore/writer/core/write_request.py
datastore/writer/core/writer.py
datastore/writer/core/writer_service.py
datastore/writer/flask_frontend/json_handlers.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
tests/shared/unit/util/test_exceptions.py
tests/writer/system/write/test_invalid_format.py
tests/writer/system/write/test_migration_index.py
tests/writer/system/write/test_write.py
tests/writer/unit/flask_frontend/test_json_handlers.py

closes https://github.com/OpenSlides/openslides-manage-service/issues/58

Allow providing a migration index in the initial write request

---

cli/create_initial_data.py
cli/export_data_only.py
cli/import_data_only.py
datastore/reader/core/reader.py
datastore/reader/core/reader_service.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/read_database.py
tests/reader/system/get_everything/test_get_everything.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py

Use the double-dict format for model im-/export, create_initial_data,
get_everything request.
Supersedes #145

Changed model format

---

LICENSE
dc.dev.yml
dc.external.yml
docs/development.md

Sets all references form master to main.
Explicitly pull from main in other docker contexts

Set various remote path to main

---

Dockerfile
Dockerfile.dev
Dockerfile.test
datastore/reader/core/reader_service.py
datastore/shared/typing.py
datastore/shared/util/self_validating_dataclass.py
requirements/requirements-general.txt
requirements/requirements-testing.txt
scripts/ci/10-black.sh
system_tests/Dockerfile

Also improve self validating dataclass behaviour.

Update to Python 3.10 and update dependencies

---

datastore/migrations/core/migrater.py
datastore/migrations/core/migrater_memory.py
datastore/migrations/core/migration_handler.py
datastore/migrations/core/setup.py
tests/migrations/system/conftest.py
tests/migrations/system/test_memory_migration.py

in-memory migration for meeting-import (Backend Issue1074)

---

datastore/shared/postgresql_backend/sql_query_helper.py
datastore/shared/util/filter.py
tests/reader/system/filter/test_filter.py

Not entirely sold on the chars `~=`, so feel free to suggest alternatives. Should work for now, however.

Add new operator for case insensitivity

---

datastore/shared/postgresql_backend/pg_connection_handler.py
dc.test.yml
requirements/requirements-testing.txt
tests/reader/system/test_client.py
tests/shared/integration/postgresql_backend/test_pg_connection_handler.py
tests/shared/unit/postgresql_backend/test_pg_connection_handler.py

Getting and putting methods with a single lock and an event to prefer releasing connections if there are no more available

Issue191 multiple transaction error

---

datastore/shared/postgresql_backend/sql_query_helper.py
tests/reader/system/filter/test_filter.py

Compare by numeric value instead of string value

---

datastore/reader/app.py
datastore/reader/core/reader_service.py
datastore/shared/services/environment_service.py
datastore/shared/util/otel.py
datastore/writer/app.py
datastore/writer/core/writer_service.py
datastore/writer/redis_backend/redis_messaging_backend_service.py
requirements/requirements-general.txt
scripts/.coveragerc
scripts/setup.cfg

Basically the datastore-equivalent to https://github.com/OpenSlides/openslides-backend/pull/1201 
Would replace #171

Opentelemetry

---

README.md
cli/README.md
cli/export_to_os3.py

usage: from inside the container, execute `python cli/export_to_os3.py <meeting-id>`. It will create the file `cli/export.sql` which you can then import in your OS3 instance.

OS3 export

---

datastore/writer/postgresql_backend/sql_occ_locker_backend_service.py
tests/writer/integration/write/test_occ_locking.py
tests/writer/system/write/test_occ_locking.py
tests/writer/unit/postgresql_backend/test_sql_occ_locker_backend_service.py

Accelerate the check for locked_fqfields for both cases, finding broken locked_fqfields and not finding one from 33/0.8sec to 2.4/0.09sec (on my laptop)

#1363 Accelerate locked_fqfields check

---

cli/export_data_only.py
datastore/reader/core/reader_service.py
datastore/reader/core/requests.py
datastore/shared/postgresql_backend/sql_query_helper.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/read_database.py
datastore/shared/util/__init__.py
datastore/shared/util/mapped_fields.py
datastore/writer/postgresql_backend/sql_database_backend_service.py
tests/reader/system/get/test_get.py
tests/reader/unit/core/test_reader_service.py
tests/shared/unit/postgresql_backend/test_sql_query_helper.py
tests/shared/unit/postgresql_backend/test_sql_read_database_backend_service.py
tests/shared/unit/util/test_mapped_fields.py
tests/writer/system/write/test_delete.py

fixes #205 
Extracted the handling of mapped fields into its own class to have the functionality bundled.

Fix fetching of too many columns

---

datastore/shared/postgresql_backend/sql_query_helper.py
datastore/shared/util/filter.py
tests/reader/system/filter/test_filter.py

resolves #187
needed for the `get_users` presenter so that the backend does not have to fetch all user to filter in-memory.

Filter by substring

---

datastore/reader/flask_frontend/json_handler.py
datastore/reader/flask_frontend/routes.py
tests/reader/system/get_everything/test_get_everything.py

needed for https://github.com/OpenSlides/openslides-backend/pull/1421

Make `get_everything` available in prod setup

---

datastore/writer/core/database.py
datastore/writer/core/writer.py
datastore/writer/core/writer_service.py
datastore/writer/flask_frontend/routes.py
datastore/writer/flask_frontend/routes_handler.py
datastore/writer/postgresql_backend/sql_database_backend_service.py
tests/writer/system/delete_history_information/test_delete_history_information.py
tests/writer/unit/core/test_writer_service.py
tests/writer/unit/postgresql_backend/test_sql_database_backend_service.py

Add route to delete history information

---

Dockerfile
Dockerfile.dev
Dockerfile.test
dc.dev.yml
dc.external.yml

Fix docker kill signals

---

README.md
datastore/shared/postgresql_backend/pg_connection_handler.py
scripts/execute-auto-formating.sh
tests/shared/unit/postgresql_backend/test_pg_connection_handler.py

@peb-adr Fixed settings, but seems to do, what it should do

#219 database failover and prolonged retry_on_db_failure

---

datastore/migrations/core/base_migration.py
datastore/migrations/core/migrater.py
datastore/migrations/core/migration_handler.py
datastore/reader/core/reader_service.py
datastore/reader/flask_frontend/routes.py
datastore/shared/postgresql_backend/pg_connection_handler.py
datastore/shared/postgresql_backend/sql_read_database_backend_service.py
datastore/shared/services/model_builder.py
datastore/shared/util/exceptions.py
datastore/shared/util/filter.py
datastore/writer/core/writer_service.py
datastore/writer/flask_frontend/json_handlers.py
datastore/writer/postgresql_backend/event_translator.py
datastore/writer/postgresql_backend/sql_database_backend_service.py
datastore/writer/redis_backend/redis_connection_handler.py
datastore/writer/redis_backend/redis_messaging_backend_service.py
requirements/requirements-general.txt
requirements/requirements-testing.txt
scripts/execute-cleanup.sh
system_tests/requirements.txt
tests/writer/integration/write/test_occ_locking.py

closes https://github.com/OpenSlides/openslides-datastore-service/pull/216

Update dependencies, pin dev dependencies, fix tests

---

datastore/shared/util/filter.py
tests/writer/integration/write/test_occ_locking.py

closes https://github.com/OpenSlides/openslides-datastore-service/issues/232

Allow fewer than 2 items in and/or lists

---

dc.dev.yml
dc.external.yml
dc.test.yml
docker-compose.yml

closes #233 
Seems like docker-compose now automatically formats the yaml files - nice

Update postgres to version 13

---

Dockerfile
cli/README.md
cli/healthcheck.py
datastore/reader/flask_frontend/routes.py
datastore/reader/flask_frontend/routes_handler.py
datastore/shared/flask_frontend/__init__.py
datastore/shared/flask_frontend/health_route.py
datastore/shared/flask_frontend/urls.py
datastore/writer/flask_frontend/routes.py
datastore/writer/flask_frontend/routes_handler.py
tests/reader/system/test_client.py
tests/reader/unit/flask_frontend/test_routes_handler.py
tests/writer/system/test_routes.py

Add healthcheck

---

datastore/migrations/core/migration_reader.py
tests/migrations/system/test_migration_reader.py

needed for https://github.com/OpenSlides/openslides-backend/pull/1739

Add status information methods to the migration reader

---

datastore/shared/util/otel.py
datastore/writer/redis_backend/redis_messaging_backend_service.py

- Write otel into redis
- prevent datastore to set trace_provider, if there is one set (integrated in backend)

I260 Write OpenTelemetry span into redis

---

datastore/shared/__init__.py

Fix signal handler

---

.github/workflows/continuous_integration.yml
Makefile
README.md
docs/development.md

Part of https://github.com/OpenSlides/OpenSlides/issues/6767

Update actions to docker compose v2

---

cli/trim_collectionfield_tables.py
reader/entrypoint.sh
scripts/system/export-database-variables.sh
tests/cli/system/test_trim_collectionfield_tables.py
writer/entrypoint.sh

The env vars required in the check were actually missing, so collection fields did not get trimmed in the past ...

Fix automatic trimming of collectionfield tables
